server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: synthetic-human-core-starter

  profiles:
    active: local

  jackson:
    time-zone: UTC
    date-format: dd-MM-yyyy'T'HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  weyland:
    audit:
      mode: CONSOLE
      kafka:
        bootstrap-servers: localhost:9092
        topic: synthetic-audit
    command:
      queue:
        max-size: 1000
      executor:
        core-pool-size: 5
        max-pool-size: 10
        keep-alive-time: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    ru.romanov.weyland.yutani.synthetic: INFO
    org.springframework.kafka: WARN
    org.springframework.aop: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/synthetic-human.log