server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: bishop-prototype

  profiles:
    active: local

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: dd-MM-yyyy'T'HH:mm:ss
    time-zone: UTC

  weyland:
    audit:
      mode: CONSOLE
      kafka:
        bootstrap-servers: localhost:9092
        topic: bishop-audit
    command:
      queue:
        max-size: 1000
      executor:
        core-pool-size: 5
        max-pool-size: 10
        keep-alive-time: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    ru.romanov.weyland.yutani.bishop: DEBUG
    ru.romanov.weyland.yutani.synthetic: INFO
    org.springframework.kafka: WARN
    org.springframework.aop: DEBUG
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bishop-prototype.log